feat(#3) : provide global response
EONEDU/EONEDU_Back pull request #7
Opened 2024-08-04 09:01 UTC by ohhamma

## 📌 연관된 이슈
- #3 

## 📝 작업 내용
- 커스텀 에러 코드를 관리하는 `ErrorCode` 추가
- `CustomException` 추가
- 모든 예외는 `ErrorResponse`로 감싸도록 핸들링
- 모든 응답을 `GlobalResponse`로 감싸도록 핸들링

## 🌳 작업 브랜치명
- `feat/3-global-response`

## 📸 스크린샷 (선택)

## 💬 리뷰 요구사항 (선택)

2024-08-04 10:03 UTC, kimsh1017 requested changes

2024-08-04 11:28 UTC, ohhamma commented on src/main/java/com/eonedu/global/error/GlobalExceptionHandler.java
음 이 부분은 매개변수 개수가 많지 않아서 정적 팩토리 메소드 패턴을 사용했는데, 빌더 패턴을 원하시는 이유가 있을까요

2024-08-04 16:18 UTC, ohhamma commented on src/main/java/com/eonedu/global/error/GlobalExceptionHandler.java
앗 `GlobalExceptionHandler`에 첨부한 코멘트군요! 중복 코드 줄이는 메소드 하나 더 추가하겠습니다.

2024-08-07 14:51 UTC, ohhamma commented on src/main/java/com/eonedu/global/error/GlobalExceptionHandler.java
메소드로 따로 분리했습니다!

2024-08-07 14:53 UTC, kimsh1017 approved these changes
최고에요

2024-08-07 14:54 UTC, kimsh1017 approved these changes

2024-08-07 14:54 UTC, merged