feat(#2) : Reservation API 개발
EONEDU/EONEDU_Back pull request #8
Opened 2024-08-07 05:35 UTC by kimsh1017

## 📌 연관된 이슈
-  #2 

## 📝 작업 내용
- 사용자용 Reservation API 개발 (API 명세 - No.1)
- `Reservation`, `ClientReservation`, `AdminReservation` SingleTable 상속 전략 써서 Entity 생성
- `Reservation`과 연결되는 `Branch`, `CounselType` Entity 생성
- 예약 시간 관리하는 `ReservationTime` Enum 생성

## 🌳 작업 브랜치명
-  `feat/2-reservation`

## 📸 스크린샷 (선택)

## 💬 리뷰 요구사항 (선택)
- 예외 처리 공통 로직이 dev에 머지가 아직 안되서 지금은 IllegalArgumentException()만 사용해서 대충 처리했습니다.
- 제가 사용해봤던 방식으로 일단 Branch만 IntegrationTest 넣어봤습니다. 의견 있으면 부탁드립니다.
- 예외처리 공통 로직 PR 후에 custom Exception 써서 예외처리 로직과 통합 테스트 로직 추가하겠습니다.

2024-08-07 14:53 UTC, ohhamma commented on src/main/java/com/eonedu/domain/branch/domain/Branch.java
> +    private int id;
id값을 `int`로 정하신 이유가 있나요? Long으로 변경하는게 더 좋을 것 같습니다.

2024-08-07 14:53 UTC, ohhamma commented on src/main/java/com/eonedu/domain/branch/domain/Branch.java
> +    @Column(nullable = false)
다른 필드들도 칼럼 이름을 정해주면 좋을 것 같아요 !

2024-08-07 15:04 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/domain/Reservation.java
> +    @ManyToOne(fetch = FetchType.LAZY)
다른 엔티티와 매핑할 떄 `optional`이라는 필드가 있는데, 기본값이 true이기 때문에 명시적으로 `false` 선언을 해줘야 할 것 같아요.

2024-08-07 15:07 UTC, ohhamma commented on .github/workflows/dev_depoly_build.yml
모든 명령어마다 `sudo`를 사용하는 이유가 있나요?

2024-08-07 15:12 UTC, ohhamma commented on src/main/java/com/eonedu/domain/branch/dto/request/BranchCreateRequest.java
> +public class BranchCreateRequest {
dto는 일반 클래스 대신 레코드를 써보는건 어떤가요?

2024-08-07 15:15 UTC, ohhamma commented on src/main/java/com/eonedu/domain/counseltype/domain/CounselType.java
> +@Getter @Setter
저희 entity에는 setter 사용하지 않는 패턴으로 가는 게 더 좋을 것 같아요.

2024-08-07 15:17 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/application/ReservationService.java
> +                .orElseThrow(() -> new IllegalArgumentException("Branch not found"));
이번에 생성한 `CustomException`을 상속받는 예외를 던지도록 수정해봅시다.

2024-08-07 15:19 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/api/ReservationController.java
> +            return new ReservationByDateResponse(reservations);
controller 로직이 조건에 의해서 너무 분기되는 것 같아요. 쿼리를 한번에 처리하는 로직을 서비스 계층에 따로 넣는 게 좋을 것 같습니다.

2024-08-07 15:21 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/api/ReservationController.java
> +        return "Reservation deleted";
정상적으로 삭제되었을 때 저희 `204`가 아니라 문자열 반환하나요?

2024-08-07 15:21 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/api/ReservationController.java
> +        return reservation.getId();
응답이 설령 id값 하나만 들어있어도 응답 dto를 만들어주는 게 좋을 것 같습니다.

2024-08-07 15:22 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/dto/response/ClientReservationUpdateResponse.java
> +    public ClientReservationUpdateResponse(ClientReservation reservation) {
응답 dto에서도 정적 팩토리 메소드를 사용해봅시다.

2024-08-07 15:24 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/api/ReservationController.java
> +            return new ReservationByDateResponse(reservations);
이후에 수정되었군요. 확인했습니다1

2024-08-07 15:24 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/api/ReservationController.java
> +            return new ReservationByDateResponse(reservations);
메소드명만 `findExistingReservations`로 변경해주시면 좋을 것 같아요.

2024-08-07 15:26 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/application/ReservationService.java
>      private void isReservationPossible(CounselType counselType, Branch branch, LocalDate date, ReservationTime time){
유효성 검증하는 메소드명은 `validate` 키워드로 시작하게끔 통일합시다.
이 경우에는 `validatePossibleReservation`으로 가면 좋을 것 같습니다 !

2024-08-07 15:27 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/dto/response/ClientReservationCreateResponse.java
생성 요청에 대한 응답 dto 생성하신 부분 확인헀습니다!

2024-08-07 15:30 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/application/ReservationService.java
> +        if (!reservation.getClientName().equals(clientName) || !reservation.getClientPhone().equals(clientPhone)){
사소한 내용이지만, client가 일치하는 경우에 대한 boolean값을 변수로 따로 두고 if문에서 그 변수를 활용하는 형식으로 구현하는 건 어떤가요? 가독성이 더 좋아질 것 같습니다.

2024-08-07 15:35 UTC, ohhamma commented on src/test/java/com/eonedu/domain/branch/BranchIntegrationTest.java
> +        String request = "{ \"name\": \"강남점\" }";
테스트 만들 때 json 직접 만들지 않아도 아래의 메소드를 사용해서 요청 dto 객체를 json으로 생성 가능해요 !
```java
BranchCreateRequestDto branchCreateRequest = BranchCreateRequestDto("강남점");
new ObjectMapper().writeValueAsString(branchCreateRequest)
```

2024-08-07 15:36 UTC, ohhamma commented on src/test/java/com/eonedu/domain/branch/BranchIntegrationTest.java
> +public class BranchIntegrationTest {
통합 테스트에서는 `@Transactional`도 같이 붙여줍시다.

2024-08-07 15:38 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/dto/request/RequestClientInformation.java
> +public class RequestClientInformation {
요청 dto 형식은 `000Request`으로 통일합시다. 뒤에 dto 키워드까지 같이 붙일지는 같이 정해보죠.

2024-08-07 15:39 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/domain/ReservationState.java
>      WAITING, CONFIRMED, CANCELED
각 enum에 대해서 한글값도 같이 주면 좋을 것 같아요.
```java
WAITING("대기중"),
CONFIRMED("승인됨"),
CANCELED("취소됨"),
;
```

2024-08-07 15:40 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/domain/ReservationState.java
>      WAITING, CONFIRMED, CANCELED
그래서 저 값대로 프론트에 넘겨주면 좋을 것 같습니다.

2024-08-07 15:41 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/api/ReservationController.java
> +    // 상담 예약 생성하는 API
주석을 남기는 것도 좋지만, swagger를 사용해서 각 api마다 description을 남기는건 어떤가요? api 문서화도 간편하게 할 수 있어서 좋을 것 같습니다 !

2024-08-07 15:44 UTC, ohhamma requested changes
작성하신 코드 모두 확인했습니다! 몇 가지 변경 사항들이 있어보여 코멘트로 남겨두었으니, 확인하시고 수정해서 다시 push 부탁드립니다. 현재 공통 응답 로직도 머지되었으니 `dev` 브랜치를 여기 브랜치에 병합받아서 계속 진행해주시면 됩니다 !

2024-08-09 01:12 UTC, ohhamma commented on src/main/java/com/eonedu/domain/branch/dto/response/BranchFindAllResponse.java
`BranchResponse`를 아예 다른 레코드로 분리하는게 좋을 것 같아요.

2024-08-09 01:15 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/dto/request/ClientReservationCreateRequest.java
각 constraints 어노테이션들에도 개별적으로 메시지 넣어주세요.

2024-08-10 12:05 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/api/ReservationController.java
> +        return "Reservation deleted";
넵 그렇게 하는게 좋을 것 같습니다 !

2024-08-10 12:20 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/api/ReservationController.java
> +                                                           @RequestParam LocalDate date){
저희 API 명세에 맞게 쿼리 매개변수 이름 맞춰주세요! `value` 옵션 사용하시면 됩니다.

2024-08-10 12:22 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/api/ReservationController.java
> +            return ReservationByDateResponse.from(reservations);
controller와 service 메소드명 모두 `findPossibleReservations`로 변경 부탁드립니다. 여러 값을 반환하기 때문에 복수형이 좋을 것 같습니다 !

2024-08-10 12:23 UTC, ohhamma commented on src/main/java/com/eonedu/domain/counseltype/dto/request/CounselTypeCreateRequest.java
모든 request 필드애는 `@NotNull` 붙여줘야 null 체크가 가능합니다 !

2024-08-10 12:27 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/application/ReservationService.java
> +                .orElseThrow(() -> new IllegalArgumentException("CounselType not found"));
이 부분은 각 `Branch`와 `CounselType`의 레포지토리 메소드를 직접 사용하는 것이 아닌, 각 엔티티의 서비스에 해당 메소드를 생성한 뒤 호출해와야 할 것 같습니다. 또, 각 엔티티에 해당하는 커스텀 예외를 생성해서 던지도록 수정 부탁드립니다.

2024-08-10 12:28 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/application/ReservationService.java
> +                .orElseThrow(() -> new IllegalArgumentException("CounselType not found"));
이 부분도 위와 동일하게 수정 부탁드립니다.

2024-08-10 12:29 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/application/ReservationService.java
> +                        throw new IllegalArgumentException("Reservation already exists");
예약과 관련된 커스텀 예외를 생성해서 던져주는 형식으로 수정 부탁드립니다.

2024-08-10 12:29 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/application/ReservationService.java
> +        if (!reservation.getClientName().equals(clientName) || !reservation.getClientPhone().equals(clientPhone)){
넵 맞습니다 !

2024-08-10 12:31 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/domain/ReservationState.java
>      WAITING, CONFIRMED, CANCELED
이 경우 프론트에서는 각 enum 값을 어떻게 받나요? 프론트에서 예약 상태를 어떻게 보여주는지에 따라 수정 여부를 같이 결정해보면 좋을 것 같습니다.

2024-08-10 12:32 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/domain/ReservationTime.java
> +    public static ReservationTime find(String time){
`findByTimeString`으로 메소드명 변경 부탁드립니다 !

2024-08-10 12:35 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/domain/ReservationTime.java
> +        for(ReservationTime reservationTime : ReservationTime.values()){
사소한 부분이지만, for를 사용하지 않고 `stream()`과 `filter()`를 사용해서 반환하는 형식으로 바꾸는 게 좋을 것 같습니다. 이 경우 `findFirst()`를 사용할 경우 Optional 객체를 반환하는데 nullable한 결과값을 리턴하는 대신 디폴트 `NONE("")` 값을 enum에 추가해서 일치하는 값이 없는 경우에 `orElse()`를 사용해서 리턴하도록 수정하는 건 어떨까요?
```java
return ReservationTime.values().stream()
                .filter(time -> reservationTime.getTimeString.equals(time))
                .findFirst()
                .orElse(NONE);
```

2024-08-10 12:52 UTC, kimsh1017 commented on src/main/java/com/eonedu/domain/reservation/application/ReservationService.java
> +                .orElseThrow(() -> new IllegalArgumentException("CounselType not found"));
서비스 레이어가 분리된 이유를 생각하면 서비스 레이어에서 다른 서비스를 호출하는 건 아닌 것 같아요.
Branch 서비스의 비즈니스 로직이 필요한 게 아니라, 특정 branch 데이터가 db에 존재하는지 확인하는게 목적이면 레포지토리를 사용하는게 맞다고 생각합니다.
branch는 나중에 학원 접수에도 사용될텐데 서비스끼리 의존관계가 생기면 순환참조의 위험성도 생기지 않을까요?

2024-08-10 13:08 UTC, kimsh1017 commented on src/main/java/com/eonedu/domain/reservation/domain/ReservationTime.java
> +        for(ReservationTime reservationTime : ReservationTime.values()){
그렇게 사용하면 findByTimeString()을 호출할때마다 반환값이 NONE인지 체크하고 예외를 던지는 로직을 같이 써줘야 합니다.
혹시 까먹고 빠트리면 예약 시간에 NONE이 들어간 상태로 예약이 저장되거나, 수정된다던가 하는 일이 일어날 것 같아요.

```java
return Arrays.stream(ReservationTime.values())
                .filter(reservationTime -> reservationTime.getTimeString().equals(timeString))
                .findAny()
                .orElseThrow(() -> new InvalidTimeStringException("예약 가능 시간이 아닙니다."));
```

이렇게 수정하는건 어떨까요??

2024-08-10 13:30 UTC, kimsh1017 commented on src/main/java/com/eonedu/domain/reservation/api/ReservationController.java
> +                                                           @RequestParam LocalDate date){
추가했습니다

2024-08-10 13:31 UTC, kimsh1017 commented on src/main/java/com/eonedu/domain/reservation/api/ReservationController.java
> +            return ReservationByDateResponse.from(reservations);
좋습니다. 변경했습니다

2024-08-10 13:31 UTC, kimsh1017 commented on src/main/java/com/eonedu/domain/reservation/application/ReservationService.java
> +                        throw new IllegalArgumentException("Reservation already exists");
ReservationService에서 customException 던지도록 수정했습니다

2024-08-10 13:32 UTC, kimsh1017 commented on src/main/java/com/eonedu/domain/reservation/domain/ReservationTime.java
> +    public static ReservationTime find(String time){
수정했습니다

2024-08-10 14:57 UTC, kimsh1017 commented on src/main/java/com/eonedu/domain/counseltype/dto/request/CounselTypeCreateRequest.java
@NotBlank가 null 체크 + 공백문자열 체크 기능 같이 해주는걸로 알고 있습니다

2024-08-10 16:12 UTC, kimsh1017 commented on src/main/java/com/eonedu/domain/branch/dto/response/BranchFindAllResponse.java
수정했습니다

2024-08-10 16:38 UTC, ohhamma commented on src/main/java/com/eonedu/domain/counseltype/dto/request/CounselTypeCreateRequest.java
확인했습니다 !

2024-08-10 16:40 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/application/ReservationService.java
> +                .orElseThrow(() -> new IllegalArgumentException("CounselType not found"));
이해했습니다. 말씀해주신 것처럼 복잡한 비즈니스 로직을 사용하는 것이 아니기 때문에 레포지토리의 메소드를 바로 호출해도 괜찮을 것 같습니다.

2024-08-10 16:49 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/application/ReservationService.java
> +                .orElseThrow(() -> new IllegalArgumentException("CounselType not found"));
그러나 조금 우려되는 점은 레포지토리가 교체되는 경우에 서비스에서 레포지토리 메소드를 사용하는 경우, 해당 서비스 메소드의 로직만 변경하면 됩니다. 반면에, 레포지토리의 메소드를 그대로 사용하는 경우에는 메소드를 호출하는 코드를 모두 변경해야 할 뿐만 아니라 추가되는 로직이 생길 수도 있기 때문에 유지보수 관점에서 조금 아쉬운 점이 있는 것 같습니다.

사실 이 논의는 어떤 프로젝트에서도 항상 나오는 주제인 것 같습니다.. 성훈님의 이야기도 분명 일리가 있기 때문에 결정하기 쉽지 않네요. 내일 회의에서 같이 정해보면 좋을 것 같습니다 !

2024-08-10 16:50 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/domain/ReservationTime.java
> +        for(ReservationTime reservationTime : ReservationTime.values()){
이렇게 구현하는 방법도 있겠군요. 더 좋은 것 같습니다 ! :)

2024-08-10 16:51 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/api/ReservationController.java
> +            List<Reservation> reservations = reservationService.findExistedReservations(branchId, counselTypeId, date);
이 메소드도 `Existsing`으로 변경 부탁드립니다.

2024-08-10 16:53 UTC, ohhamma commented on src/main/java/com/eonedu/global/error/exception/ErrorCode.java
> +	RESERVATION_UUID_NOT_FOUND(HttpStatus.NOT_FOUND, "예약번호가 올바르지 않습니다."),
이 경우에는 `INVALID` 키워드가 더 적합할 것 같습니다.

2024-08-10 16:54 UTC, ohhamma commented on src/main/java/com/eonedu/global/error/exception/ErrorCode.java
> +	CLIENT_INFORMATION_DOES_NOT_MATCH(HttpStatus.BAD_REQUEST, "예약자 정보가 일치하지 않습니다."),
`DOES` 키워드는 없어도 괜찮을 것 같습니다 !

2024-08-10 16:54 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/domain/ReservationTime.java
> +        for(ReservationTime reservationTime : ReservationTime.values()){
구현하신 내용 확인했습니다.

2024-08-10 16:55 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/application/ReservationService.java
> +                        throw new IllegalArgumentException("Reservation already exists");
확인했습니다!

2024-08-11 08:54 UTC, kimsh1017 commented on src/main/java/com/eonedu/global/error/exception/ErrorCode.java
> +	RESERVATION_UUID_NOT_FOUND(HttpStatus.NOT_FOUND, "예약번호가 올바르지 않습니다."),
넵 수정했습니다

2024-08-11 08:54 UTC, kimsh1017 commented on src/main/java/com/eonedu/global/error/exception/ErrorCode.java
> +	CLIENT_INFORMATION_DOES_NOT_MATCH(HttpStatus.BAD_REQUEST, "예약자 정보가 일치하지 않습니다."),
이것도 수정했습니다

2024-08-11 13:16 UTC, ohhamma approved these changes
수정하신 부분 모두 확인했습니다! 수고하셨습니다.

2024-08-11 13:30 UTC, ohhamma commented on src/main/java/com/eonedu/domain/reservation/dto/request/RequestClientInformation.java
> +public class RequestClientInformation {
`ClientReservationRequest`로 가는 것 좋습니다 !

2024-08-11 13:32 UTC, ohhamma commented on src/main/java/com/eonedu/domain/branch/domain/Branch.java
> +    @Column(nullable = false)
네 맞습니다 !

2024-08-11 13:38 UTC, ohhamma commented on src/main/java/com/eonedu/domain/branch/domain/Branch.java
음 명시해주면 좋을 것 같다고 생각했었는데, 클래스 이름만으로 구별이 가능하다면 명시를 안해도 될 것 같습니다 !

2024-08-11 13:50 UTC, merged